### ISSUE TITLE
GELF via HTTP Support?

### ISSUE THREAD

**Issue by CarlosSardo** [Pliner/EasyGelf#13]
Hi,

Quick question: does your library support GELF via HTTP? As described here:

http://docs.graylog.org/en/latest/pages/sending_data.html#what-are-graylog-message-inputs

thanks!

**Comment by CarlosSardo** [comment]
Hi,

I would like to contribute to your project. I have a local branch that I would like to submit and perhaps create a pull request to the master, out of it. 

Can you add me as project contributor?

**Comment by Pliner** [comment]
Hi @CarsolSardo! 

Thank you for interesting in contribution to EasyGelf. Pull requests are welcome :-)

It seems I've never checked written http appender, so it can be broken :sad: I am in journey and can't check it...

**Comment by CarlosSardo** [comment]
Can you add me to the repo?

**Comment by Pliner** [comment]
@CarlosSardo  Pull requests work in different way. https://help.github.com/articles/using-pull-requests/
You don't need any repository access to make changes and create pull request. Just:
1) Fork EasyGelf repo
2) Make all changes in your forked EasyGelf repo
3) Commit & Push
4) Create Pull Request

**Comment by CarlosSardo** [comment]
thanks, will do! I've been using it bitbucket.org in a different way :)

**Comment by Pliner** [comment]
@CarlosSardo thank you too :smile:
